version: '3'

services:
  web:
    build: .
    command: ["./init.sh"]
    environment:
      - "DJANGO_SETTINGS_MODULE=rucio_opint_backend.apps.core.settings"
      - "PYTHONPATH=/code:${PYTHONPATH}"
      - "ADMIN_PASSWORD=replace_with_admin_password"
      - "API_KEY=replace_with_app_key"
    volumes:
      - .:/code
    privileged: true
    ports:
      - "8080:8080"
    restart: always